<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exce√ß√µes e Tratamento de Erros</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,200..800&family=Cascadia+Code:ital,wght@0,200..700;1,200..700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="css/aulas.css">
    <link rel="shortcut icon" href="assets/logopython.png" type="image/x-icon">
</head>

<body>
    <header class="class-header">
        <h1 style="margin: 0;"><a href="index.html" style="text-decoration: none; color: currentColor;">Curso de
                Python</a></h1>
        <span style="font-size: 1.2em; font-weight: bold;">Aula 18 - Exce√ß√µes e Tratamento de Erros</span>
    </header>
    <div class="container">
        <main>
            <h1>Exce√ß√µes e Tratamento de Erros</h1>
            <p>Exce√ß√µes s√£o essenciais num programa para mostrar uma mensagem menos assustadora, mas n√£o s√≥ por causa
                disso, os erros tamb√©m s√£o um p√©ssimo vil√£o, uma vez que n√£o foram identificados, o programa todo se
                quebra e o usu√°rio fica perdido. As exce√ß√µes tratam erros gerais, mas voc√™ pode especificar qual erro
                deseja tratar.</p>

            <h2>Sintaxe B√°sica</h2>
            <div class="example-code-container">
                <div class="example-code-header">
                    <div class="dots">
                        <div class="dot red"></div>
                        <div class="dot yellow"></div>
                        <div class="dot green"></div>
                    </div>
                    <span>sintaxe_try_except.py</span>
                </div>
                <pre class="example-pre"><code>try:
    # bloco de c√≥digo
except:
    # mensagem de erro</code></pre>
            </div>
            <p>Primeiramente utilizamos o <code>try</code>, e dentro de seu bloco de c√≥digos inserimos o c√≥digo que √©
                suspeito de falhas. Logo em seguida, fora do bloco de c√≥digos do <code>try</code>, utilizamos o
                <code>except</code>, e no bloco de c√≥digo do <code>except</code> colocamos os c√≥digos que ser√£o exibidos
                caso ocorra algum erro.</p>

            <h2>Exemplos Pr√°ticos</h2>
            <h3>Exemplo 1: Tratando um Erro de Divis√£o</h3>
            <p>Vamos ver o seguinte exemplo em que tentamos dividir uma <code>STRING</code> por um <code>INT</code>:</p>
            <div class="example-code-container">
                <div class="example-code-header">
                    <div class="dots">
                        <div class="dot red"></div>
                        <div class="dot yellow"></div>
                        <div class="dot green"></div>
                    </div>
                    <span>erro_divisao.py</span>
                </div>
                <pre class="example-pre"><code>try:
    divisao = 3 / "string"
    print(divisao) # Isso sempre dar√° um erro porque n√£o √© poss√≠vel dividir um inteiro por uma string.
except:
    print("Ocorreu um erro!")</code></pre>
                <div class="example-output-container">
                    <div class="example-output-header">Sa√≠da:</div>
                    <div class="output">
                        <pre>Ocorreu um erro!</pre>
                    </div>
                </div>
            </div>

            <h3>Exemplo 2: Tratando Erros com Input do Usu√°rio</h3>
            <p>√â muito recomendado que se utilize tratamento de erros em todo programa que voc√™ for criar, especialmente
                quando √© utilizado a intera√ß√£o com o usu√°rio (os <code>inputs</code>), mesmo que voc√™ n√£o suspeite que
                aconte√ßa erros. Vamos ver um exemplo geral:</p>
            <div class="example-code-container">
                <div class="example-code-header">
                    <div class="dots">
                        <div class="dot red"></div>
                        <div class="dot yellow"></div>
                        <div class="dot green"></div>
                    </div>
                    <span>soma_com_input.py</span>
                </div>
                <pre class="example-pre"><code>try:
    n1 = int(input('Digite o primeiro n√∫mero: '))
    n2 = int(input('Digite o segundo n√∫mero: '))
    print(f'A soma entre {n1} e {n2} √© {n1 + n2}')
except:
    print('Ops! N√£o foi poss√≠vel calcular a soma entre os dois n√∫meros!')</code></pre>
            </div>
            <p>Aqui tentamos realizar a soma entre <code>n1</code> e <code>n2</code>, mas surge uma pergunta: "Como que
                isso pode dar um erro?". Uma das respostas √© se o usu√°rio digitar um n√∫mero decimal
                (<code>float</code>), isso causaria um erro porque declaramos <code>n1</code> e <code>n2</code> como
                inteiros, e n√£o decimais. Outra poss√≠vel falha √© caso o usu√°rio n√£o digitasse nada e apenas apertasse
                <code>ENTER</code>, isso tamb√©m seria um erro pois <code>ENTER</code> √© um valor nulo, n√£o um inteiro.
            </p>

            <div class="button-container">
                <button id="left-button" class="nav-button" onclick="location.href='aula017.html'">Aula
                    anterior</button>
                <button id="center-button" class="nav-button" onclick="location.href='bot.html'">√Årea de Testes</button>
                <button id="right-button" class="nav-button" onclick="location.href='aula019.html'">Pr√≥xima
                    Aula</button>
            </div>
        </main>
    </div>
    <button id="toggle-theme">üåô</button>
    <script src="scripts/script.js"></script>
</body>

</html>